# metallb-config.yaml
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: lb-addresses
  namespace: kube-system # adjust to your preference
spec:
  addresses:
    - 192.168.50.240-192.168.50.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: lb-addresses
  namespace: kube-system
spec:
  ipAddressPools:
    - lb-addresses
